### ISSUE TITLE
Ring thin when scale applied

### ISSUE THREAD

**Issue by GuillemGongora** [tmhglnd/mercury#22]
I was thoroughly testing the transformation methods of the rings and came across something that could be improved. When applying a scale to a ring and thinning said ring some of the notes are repeated even though having the same scale note applied to them.
I.e.:
`set scale minor c
ring notes (0 1 2 3 4 5 6 7)
ring notes thin(notes)`
sounds like:
`ring notes (0 0 2 3 3 5 7 7)`
when it should maybe sound like:
`ring notes (0 2 3 5 7)`

I think it's a matter of applying the scale to the ring before transforming it, but I think in thin() doesn't make sense that some notes are repeated after the transformation.

**Comment by tmhglnd** [comment]
Yes, this is because the scale is always applied at the end of the chain in the synth itself, not in between transformations. Maybe i could include something like `toScale()` or `conformScale()` or whatever method that lets you translate a ring to the notes of a scale. Any ideas/suggestions on this?

So for example:
```java
set scale minor c

ring notes [0 1 2 3 4 5 6 7]
ring notes toScale(notes)
//=> [0 0 2 3 3 5 7 7]
ring notes thin(notes)
//=> [0 2 3 5 7]
```

**Comment by tmhglnd** [comment]
This is now included in the latest commit as `toScale()`, and working as in the example above. The method maps the relative intervals to the scale, the root of the scale is excluded (and only applied in the synth when the note is played)
