### ISSUE TITLE
Collision between set scale and detune()

### ISSUE THREAD

**Issue by GuillemGongora** [tmhglnd/mercury#35]
`Detune()` still appears to be working in the latest version but it causes weird glitches with `set scale`, probably due to the latter applying the scale to the integers of the list, but not the decimals.
Would be useful to think what the function of `detune()` is within the environment: what should happen if `set scale` and `detune()` appear together.
And `detune()` needs to be added to the documentation.

**Comment by tmhglnd** [comment]
Fixed in 37704fbb5c997de366819747ed4b410a58f983d5. It works as expected, but indeed it lacked proper documentation. I also made a slight change from `detune()` to `useDetune()` to clarify that it is only an enable/disable method, it doesn't actually set the detuning amount.

Basic example:

```java
new synth sine shape(1 2000) time(1) note(7 2)
// => plays a perfect fifth in the second octave

new synth sine shape(1 2000) time(1) note(7.5 2) useDetune(1)
// => plays a perfect fifth + a detune of 50 cents
```

Detune is applied after scale mapping:

```java
set scale major c

new synth sine shape(1 2000) time(1) note(3 2)
// => plays a major third (mapped because of set scale)

new synth sine shape(1 2000) time(1) note(3.5 2) useDetune(1)
// => plays a major third + a detune of 50 cents
```

Currently wondering if it would be better to have `useDetune()` default to enabled? For most ring methods the result is always an integer, so it does not clash with that. Not sure what is best. Maybe I'll implement a global `set useDetune 1` so all instruments default to use the detuning.
