### ISSUE TITLE
Text overflowing at right margin

### ISSUE THREAD

**Issue by GuillemGongora** [tmhglnd/mercury#36]
Exact same thing that happened at the bottom of the window (#29), but also happens when reached a large amount of characters before the line automatically switches.

**Comment by tmhglnd** [comment]
Now fixed in c309fda19dd426fe93a774d12369e28b8e205703. Added a new menu `Editor Setup` under `Settings` with a few parameters for adjusting the text:

- font => default = Courier New
- line spacing => the distance between lines
- character spacing => the distance between characters
- relative size => scale the text extra 
- position => adjust the x and y position of the text in the window
